export function helpText(): string {
  return [
    'QuantOps CLI — Codex-first quant research harness (headless)',
    '',
    'Primary flow:',
    '  Human asks Codex what to investigate.',
    '  Codex calls rtk commands with --json.',
    '  QuantOps returns local artifacts, data checks, stats, research context, events, backtests, and session handoff.',
    '',
    'Start:',
    '  rtk codex-guide --json',
    '  rtk runtime info --json',
    '  rtk doctor',
    '',
    'Data and analysis:',
    '  rtk symbol search TSM --json',
    '  rtk data info TSM --json',
    '  rtk data download TSM --period 5y --json',
    '  rtk data download TSM --source alphavantage|twelve|polygon|fmp --period 1y --json',
    '  rtk data validate TSM --json',
    '  rtk stats TSM --json',
    '  rtk compare TSM SOXX NVDA --json',
    '  rtk research TSM --topic "earnings momentum" --json',
    '',
    'Events, backtests, and handoff:',
    '  rtk event define --type earnings --target-symbol TSM --benchmark SOXX --json',
    '  rtk event study TSM --event-date YYYY-MM-DD --benchmark SOXX --json',
    '  rtk backtest strategies --json',
    '  rtk backtest run TSM --strategy ma-cross --json',
    '  rtk session current --json',
    '  rtk session list --json',
    '  rtk session handoff <SESSION_ID>',
    '',
    'Setup:',
    '  node ./src/cli.ts setup bin',
    '  rtk setup rust',
    '  rtk sources alphavantage',
    '  rtk provider list --json',
    '',
    '한국어 안내:',
    '  Codex에게 한국어로 질문해도 됩니다. Codex가 필요한 rtk ... --json 명령을 호출하고, QuantOps는 데이터/검증/리서치/백테스트 결과를 반환합니다.',
    '',
    'Safety:',
    '  No buy/sell/hold advice. Trading mutations are disabled by default; broker/tossctl checks are optional diagnostics.',
  ].join('\n');
}
