export function helpText(): string {
  return [
    'QuantOps CLI — Codex-first quant research harness',
    '',
    'Primary flow:',
    '  Human talks to Codex in tmux/Codex session.',
    '  Codex calls rtk commands with --json.',
    '  QuantOps returns local artifacts, data checks, stats, research context, events, and backtests.',
    '',
    'Start:',
    '  rtk codex-guide',
    '  rtk runtime info --json',
    '  rtk doctor',
    '  rtk tools list --json',
    '',
    'Data and analysis:',
    '  rtk symbol search TSM --source yahoo',
    '  rtk data download TSM --period 5y --json',
    '  rtk data validate TSM --json',
    '  rtk stats TSM --json',
    '  rtk compare TSM SOXX NVDA --json',
    '  rtk research TSM --topic "earnings momentum" --json',
    '',
    'Strategy workflow:',
    '  rtk idea new "TSM earnings momentum"',
    '  rtk idea add-symbol latest TSM',
    '  rtk lab workflow latest --json',
    '  rtk event study TSM --event-date YYYY-MM-DD --benchmark SOXX --json',
    '  rtk backtest run TSM --strategy ma-cross --json',
    '',
    'Setup:',
    '  node ./src/cli.ts setup bin',
    '  rtk setup rust',
    '',
    'Safety:',
    '  Trading mutations are disabled by default. Broker/tossctl checks are optional integration diagnostics.',
  ].join('\n');
}
